# Generated by Django 4.0 on 2023-10-01 09:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhaar', models.CharField(max_length=200)),
                ('Pan_card', models.CharField(max_length=200)),
                ('Salary_slip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loan_Name', models.CharField(max_length=50)),
                ('Amount', models.FloatField()),
                ('Interest', models.FloatField()),
                ('EMI', models.CharField(max_length=20)),
                ('Loan_Duration', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Guarantee', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.CharField(max_length=200)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField(verbose_name=datetime.date(1111, 11, 11))),
                ('Email', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('PIN', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loan_Management_system.login')),
            ],
        ),
        migrations.CreateModel(
            name='LoanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=30)),
                ('LOANAPPLICATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loan_Management_system.loanapplication')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loan_Management_system.user')),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='LOANDETAILS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loan_Management_system.loandetails'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loan_Management_system.user'),
        ),
        migrations.CreateModel(
            name='EMI_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_Received', models.FloatField()),
                ('Status', models.CharField(max_length=30)),
                ('EMI_Pending', models.CharField(max_length=20)),
                ('Due', models.DateField()),
                ('LOANAPPLICATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loan_Management_system.loanapplication')),
            ],
        ),
    ]
