# Generated by Django 4.0 on 2023-10-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan_Management_system', '0002_loanapplication_status_alter_loanstatus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='status',
            new_name='Status',
        ),
        migrations.AddField(
            model_name='user',
            name='Status',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
