# Generated by Django 4.0 on 2023-10-07 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loan_Management_system', '0003_rename_status_loanapplication_status_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi_history',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Loan_Management_system.user'),
        ),
    ]
