# Generated by Django 4.0 on 2023-10-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan_Management_system', '0004_emi_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Acc_No',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='IFSC',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
