# Generated by Django 4.0 on 2023-10-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan_Management_system', '0005_user_acc_no_user_ifsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='Guarantee',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
