# Generated by Django 4.0 on 2023-10-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan_Management_system', '0006_loanapplication_guarantee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='Aadhaar',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='Guarantee',
            field=models.CharField(default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='Pan_card',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='Salary_slip',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='Photo',
            field=models.CharField(max_length=500),
        ),
    ]
