# Generated by Django 4.0 on 2023-11-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan_Management_system', '0010_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('ifsccode', models.CharField(max_length=100)),
            ],
        ),
    ]
