# Generated by Django 4.0 on 2023-11-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loan_Management_system', '0011_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='account',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='ifsccode',
            new_name='IFSC_CODE',
        ),
    ]
